#!/bin/sh
#
# /etc/init.d/wamqd
# Startup script for WAMQ service
#
# chkconfig: 2345 60 70
# description: WAMQ service daemon
#
# processname: WAMQ
# config: /etc/wamq.conf
# pidfile: /var/run/wamq.pid

# source function library
. /etc/rc.d/init.d/functions

RETVAL=0
TAG=wamq
PROG="WAMQ service"
LOCKFILE=/var/lock/subsys/$TAG
USER=wamq
EXEC=/usr/bin/wamq

start() {
    echo -n $"Starting $PROG:"
    if [ $current -eq 4 ]; # if status is 4 that means unknow state
    then
	failure
	echo
	echo "$PROG status is unknown"
	RETVAL=8
	return
    fi
    if [ $current -eq 0 ]; # if status is 0 that means running
    then
	failure
	echo
	echo "$PROG is already running"
	RETVAL=9
	return
    fi
    # START
    daemon --user $USER $EXEC &>/dev/null &
    RETVAL=$?
    if [ $RETVAL -eq 0 ];
    then
        touch $LOCKFILE
        success
    else
        failure
    fi
    echo
}

stop() {
    echo -n $"Stopping $PROG:"
    if [ $current -eq 4 ]; # if status is 4 that means unknow state
    then
	failure
	echo
	echo "$PROG status is unknown"
	RETVAL=8
	return
    fi
    if [[ "$current" == [123] ]]; # if status is one of the 1, 2, 3 that means dead
    then
	failure
	echo
	echo "$PROG is not started"
	RETVAL=9
	return
    fi
    # STOP
    killproc $TAG -TERM
    RETVAL=$?
    if [ $RETVAL -eq 0 ];
    then
	rm -f $LOCKFILE
	success
    else
	failure
    fi
    echo
}

status $TAG >/dev/null 2>/dev/null
current=$?
# 0 is running
# 1 dead but pid file exists
# 2 dead but subsys locked
# 3 stopped
# 4 unknown status

case "$1" in
    start)
	start
	;;
    stop)
	stop
	;;
    status)
	status $TAG
	RETVAL=$?
	;;
    *)
	echo $"Usage: $0 {start|stop|status}"
	RETVAL=1
esac

exit $RETVAL
