#!/bin/bash
#
# chkconfig: 35 90 12
# description: WAMQ server
#
# Get function from functions library

SYSTEMCTL_SKIP_REDIRECT=1
. /etc/init.d/functions

user=wamq
# Start the service WAMQ server
start() {
	echo -n "Starting WAMQ server:"
        cd /opt/wamq
        sudo -u $user wamq &
        ### Create the lock file ###
        touch /var/lock/subsys/wamq
        success
	echo
}
# Restart the service FOO
stop() {
	echo -n "Stopping WAMQ server:"
        killall -u $user
        ### Now, delete the lock file ###
        rm -f /var/lock/subsys/WAMQ
        success
	echo
}
### main logic ###
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        status WAMQ
        ;;
  *)
        echo $"Usage: $0 {start|stop|status}"
        exit 1
esac
exit 0
