#!/bin/bash
#
# chkconfig: 35 90 12
# description: WAMQ server
#
# Get function from functions library
. /etc/init.d/functions

user=wamq
# Start the service WAMQ server
start() {
		### initlog -c "echo -n Starting WAMQ server: "
        cd /opt/wamq
        sudo -u $user wamq &
        ### Create the lock file ###
        touch /var/lock/subsys/wamq
        success $"WAMQ server startup"
        echo
}
# Restart the service FOO
stop() {
        ### initlog -c "echo -n Stopping WAMQ server: "
        killall -u $user
        ### Now, delete the lock file ###
        rm -f /var/lock/subsys/WAMQ
        echo
}
### main logic ###
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        status WAMQ
        ;;
  *)
        echo $"Usage: $0 {start|stop|status}"
        exit 1
esac
exit 0
